### ISSUE TITLE
virtual machine failure on bios 3.0.6 beta 

### ISSUE THREAD

**Issue by learningandmemorylab** [FrameworkComputer/SoftwareFirmwareIssueTracker#15]
AMD 13" DIY
Virtualbox worked fine before upgrading to the 3.0.6.beta BIOS. The error message is:

VirtualBox can't enable the AMD-V extension. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_SVM_IN_USE).
Result Code:
NS_ERROR_FAILURE (0x80004005)
Component:
ConsoleWrap
Interface:
IConsole {6ac83d89-6ee7-4e33-8ae6-b257b2e81be8}

I tried reinstalling 2 versions of vbox, tested several VMs, three kernels (6.11.x, 6.12.x, 6.5.x) all to no avail. cat /proc/cpu lists "svm" for each CPU.

**Comment by jcdutton** [comment]
Are you running kvm or docker also?  You might need to rmmod kvm and stop any docker instances.
I think this explains the problem and solution quite well:
https://askubuntu.com/questions/413511/can-virtualbox-and-kvm-run-alongside-each-other

**Comment by JohnAZoidberg** [comment]
As @jcdutton indicated (thanks!) it might be a configuration issue.

As your error message says "Please disable the KVM kernel extension, recompile your kernel and reboot".
Have you tried that?

**Comment by brlin-tw** [comment]
@learningandmemorylab 

> VirtualBox can't enable the AMD-V extension. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_SVM_IN_USE).

This error message seems to indicate that the hardware virtualization support is being used by another application(e.g. KVM or VMware workstation), please ensure none of those are running and try to reproduce this issue.

You can also try booting into a live system and reproduce this problem as it won't have these kinds of things installed.

**Comment by superm1** [comment]
Try `kvm.enable_virt_at_load=0` on kernel command line.

https://9to5linux.com/virtualbox-7-1-4-adds-initial-support-for-linux-kernel-6-12-and-other-linux-changes

**Comment by learningandmemorylab** [comment]
Thank you all for your good advice.  rmmod kvm_amd let the VMs work again. Superm1's advice was right on too about the change in 6.12 behavior. superm1's help now acknowledged in the Framework community web pages.
